(function(){
'use strict';
const APP_VERSION='3.2.0-working';
const DB='bukhTaavarProV32';
const provinces=['Архангай','Баян-Өлгий','Баянхонгор','Булган','Говь-Алтай','Говьсүмбэр','Дархан-Уул','Дорноговь','Дорнод','Дундговь','Завхан','Орхон','Өвөрхангай','Өмнөговь','Сүхбаатар','Сэлэнгэ','Төв','Увс','Ховд','Хөвсгөл','Хэнтий','Улаанбаатар'];
const defaultState={currentUser:null,closed:false,activeTournament:'naadam2026',adminPin:'1234',users:[],events:[{id:'naadam2026',name:'Улсын баяр наадам 2026',type:'Улсын наадам',date:'2026-07-11T09:00:00',status:'Таавар авч байна',location:'Төв цэнгэлдэх хүрээлэн'}],wrestlers:[{id:'w1',name:'О.Хангай',rank:'Улсын аварга',province:'Ховд',photo:''},{id:'w2',name:'Б.Орхонбаяр',rank:'Улсын арслан',province:'Сэлэнгэ',photo:''},{id:'w3',name:'П.Бүрэнтөгс',rank:'Улсын аварга',province:'Увс',photo:''},{id:'w4',name:'Н.Батсуурь',rank:'Дархан аварга',province:'Увс',photo:''},{id:'w5',name:'Ц.Содномдорж',rank:'Улсын арслан',province:'Хөвсгөл',photo:''},{id:'w6',name:'Р.Пүрэвдагва',rank:'Улсын арслан',province:'Архангай',photo:''},{id:'w7',name:'Б.Гончигдамба',rank:'Улсын гарьд',province:'Завхан',photo:''},{id:'w8',name:'Д.Анар',rank:'Улсын начин',province:'Дорнод',photo:''}],predictions:[],results:null,notifications:[{title:'V3.2 ажиллах хувилбар',body:'JS замын алдааг арилгаж нэг app.js болголоо.',at:new Date().toISOString()}],settings:{points:{champion:100,runner:70,semi:40,quarter:20,province:30,title:30,combo:120}}};
let S=load(); let tab='home';
function clone(o){return JSON.parse(JSON.stringify(o))}
function load(){try{let s=localStorage.getItem(DB);return s?JSON.parse(s):clone(defaultState)}catch(e){return clone(defaultState)}}
function save(){normalizeState();localStorage.setItem(DB,JSON.stringify(S))}
function normalizeState(){
 if(!S || typeof S!=='object') S=clone(defaultState);
 if(!S.events)S.events=clone(defaultState.events); if(!S.wrestlers)S.wrestlers=clone(defaultState.wrestlers); if(!S.predictions)S.predictions=[]; if(!S.users)S.users=[]; if(!S.notifications)S.notifications=[]; if(!S.settings)S.settings=clone(defaultState.settings); if(!S.settings.points)S.settings.points=clone(defaultState.settings.points); if(!S.adminPin)S.adminPin='1234'; if(!S.activeTournament)S.activeTournament=S.events[0]?.id||'naadam2026';
 S.wrestlers=S.wrestlers.map((w,i)=> typeof w==='string'?{id:'w'+i,name:w,rank:'',province:'',photo:''}:{id:w.id||uid(),name:w.name||'',rank:w.rank||'',province:w.province||'',photo:w.photo||''});
 S.users.forEach(u=>{u.avatar=u.avatar||'';u.province=u.province||'';u.age=u.age||'';u.xp=u.xp||u.score||0;u.level=u.level||levelFromXp(u.xp);u.medals=u.medals||[];u.totalPredictions=u.totalPredictions||0;u.correctPredictions=u.correctPredictions||0;u.score=u.score||0;});
}
function uid(){return Math.random().toString(36).slice(2)+Date.now().toString(36)}
function $(q){return document.querySelector(q)}
function $all(q){return Array.from(document.querySelectorAll(q))}
function me(){return S.users.find(u=>u.id===S.currentUser)}
function currentEvent(){return S.events.find(e=>e.id===S.activeTournament)||S.events[0]}
function wrestlerName(id){return (S.wrestlers.find(w=>w.id===id)||{}).name||id||'-'}
function levelFromXp(xp){return Math.max(1,Math.floor((xp||0)/150)+1)}
function provinceOptions(v=''){return provinces.map(p=>`<option ${p===v?'selected':''}>${p}</option>`).join('')}
function wrestlerOptions(v=''){return S.wrestlers.map(w=>`<option value="${w.id}" ${v===w.id?'selected':''}>${w.name} · ${w.rank}</option>`).join('')}
function toast(msg){let old=$('.toast'); if(old)old.remove(); let d=document.createElement('div');d.className='toast';d.textContent=msg;document.body.appendChild(d);setTimeout(()=>d.remove(),2200)}
function avatarHtml(u,big=false){let letter=(u?.name||'Б')[0];return `<div class="avatar ${big?'big':''}">${u?.avatar?`<img src="${escapeAttr(u.avatar)}" onerror="this.parentNode.textContent='${letter}'">`:letter}</div>`}
function escapeAttr(s){return String(s||'').replace(/"/g,'&quot;')}
function checks(n){return $all(`input[name=${n}]:checked`).map(x=>x.value)}
function multi(name,arr=[],limit=8){return S.wrestlers.map(w=>`<label class="choice"><input type="checkbox" name="${name}" value="${w.id}" ${(arr||[]).includes(w.id)?'checked':''} onchange="BTP.limitChecks('${name}',${limit})">${w.name} <span class="muted small">${w.rank}</span></label>`).join('')}
function limitChecks(name,limit){let xs=$all(`input[name=${name}]:checked`);if(xs.length>limit){xs[xs.length-1].checked=false;toast(`Хамгийн ихдээ ${limit} сонгоно`)}}
function nav(){let items=[['home','Нүүр'],['predict','Таавар'],['mine','Минийх'],['board','Чансаа'],['profile','Профайл'],['admin','Админ']];return `<div class="tabs">${items.map(i=>`<button class="${tab===i[0]?'active':''}" onclick="BTP.setTab('${i[0]}')">${i[1]}</button>`).join('')}</div>`}
function setTab(t){tab=t;render()}
function screen(){if(tab==='home')return home();if(tab==='predict')return predict();if(tab==='mine')return mine();if(tab==='board')return board();if(tab==='profile')return profile();if(tab==='admin')return admin();return home()}
function render(){try{normalizeState();document.getElementById('app').innerHTML=`<div class="wrap"><div class="topbar"><b>Бөх Таавар Pro</b><span class="muted small">v${APP_VERSION}</span></div>${screen()}<div class="version">${APP_VERSION}</div></div>${nav()}`;}catch(e){document.getElementById('app').innerHTML=`<div class="wrap"><div class="card error"><h2>JS алдаа</h2>${String(e.stack||e)}</div></div>`;console.error(e)}}
function authBox(){let u=me(); if(u)return `<div class="card"><div class="row space"><div class="row">${avatarHtml(u)}<div><b>${u.name}</b><div class="muted small">${u.phone} · Level ${u.level} · ${u.xp} XP</div></div></div><button class="secondary" onclick="BTP.logout()">Гарах</button></div></div>`;return `<div class="card"><h2>Бүртгүүлэх / Нэвтрэх</h2><p class="muted">Эхний хувилбар localStorage дээр ажиллана. Дараагийн шатанд Firebase OTP холбоно.</p><div class="grid"><div class="span6"><label>Нэр</label><input id="name" placeholder="Нэр"></div><div class="span6"><label>Утас</label><input id="phone" placeholder="Утасны дугаар"></div><div class="span6"><label>Аймаг</label><select id="province">${provinceOptions()}</select></div><div class="span6"><label>Нас</label><input id="age" type="number" placeholder="Нас"></div><div class="span12"><button onclick="BTP.login()">Нэвтрэх / бүртгүүлэх</button></div></div></div>`}
function login(){let name=$('#name').value.trim(),phone=$('#phone').value.trim();if(!name||!phone)return toast('Нэр, утсаа оруулна уу');let u=S.users.find(x=>x.phone===phone);if(!u){u={id:uid(),name,phone,province:$('#province').value,age:$('#age').value,avatar:'',score:0,xp:0,level:1,medals:['Шинэ гишүүн'],totalPredictions:0,correctPredictions:0,createdAt:new Date().toISOString()};S.users.push(u)}S.currentUser=u.id;save();toast('Амжилттай нэвтэрлээ');render()}
function logout(){S.currentUser=null;save();render()}
function countdownHtml(){let e=currentEvent();let target=new Date(e?.date||Date.now()+86400000).getTime();let diff=Math.max(0,target-Date.now());let d=Math.floor(diff/86400000),h=Math.floor(diff/3600000)%24,m=Math.floor(diff/60000)%60,s=Math.floor(diff/1000)%60;return `<div class="countdown"><div class="timebox"><b>${d}</b><span>өдөр</span></div><div class="timebox"><b>${h}</b><span>цаг</span></div><div class="timebox"><b>${m}</b><span>мин</span></div><div class="timebox"><b>${s}</b><span>сек</span></div></div>`}
function topUsers(n=5){return [...S.users].sort((a,b)=>(b.score||0)-(a.score||0)).slice(0,n).map((u,i)=>`<div class="row space"><span>${i+1}. ${u.name}</span><b>${u.score||0}</b></div>`).join('')||'<p class="muted">Одоогоор оноо алга.</p>'}
function home(){let e=currentEvent();return `<div class="hero"><h1>Бөх Таавар Pro</h1><p class="muted">Линкээр ашиглах Монгол бөхийн оноотой тааврын PWA. Бодит мөнгөний бооцоо биш.</p>${authBox()}<h2>${e?.name||'Наадам'}</h2><p class="muted">${e?.location||''} · ${e?.status||''}</p>${countdownHtml()}<br><button onclick="BTP.setTab('predict')">Таавар өгөх</button></div><h2>Системийн төлөв</h2><div class="grid"><div class="card span3"><div class="score">${S.users.length}</div><b>Хэрэглэгч</b></div><div class="card span3"><div class="score">${S.predictions.length}</div><b>Таавар</b></div><div class="card span3"><div class="score">${S.events.length}</div><b>Наадам</b></div><div class="card span3"><div class="score">${S.closed?'Хаалттай':'Нээлттэй'}</div><b>Төлөв</b></div><div class="card span6"><h2>ТОП таамаглагч</h2>${topUsers(5)}</div><div class="card span6"><h2>Мэдэгдэл</h2>${S.notifications.slice(-4).reverse().map(n=>`<p><b>${n.title}</b><br><span class="muted small">${n.body}</span></p>`).join('')||'<p class="muted">Мэдэгдэл алга.</p>'}</div></div>`}
function predict(){if(!me())return authBox();let p=S.predictions.find(x=>x.userId===S.currentUser&&x.eventId===S.activeTournament)||{};return `<h2>Таавар өгөх</h2>${S.closed?'<div class="notice">Таавар хаагдсан байна.</div>':''}<div class="grid"><div class="card span6"><label>Наадам</label><select id="eventSel" onchange="BTP.changeEvent(this.value)">${S.events.map(e=>`<option value="${e.id}" ${S.activeTournament===e.id?'selected':''}>${e.name}</option>`).join('')}</select><br><br><label>Түрүүлэх бөх</label><select id="champion">${wrestlerOptions(p.champion)}</select><br><br><label>Үзүүрлэх бөх</label><select id="runner">${wrestlerOptions(p.runner)}</select><br><br><label>Аль аймгийн бөх түрүүлэх вэ?</label><select id="province">${provinceOptions(p.province)}</select><br><br><label>Аль цолны бөх шөвгөрөх вэ?</label><select id="title"><option ${p.title==='Аварга'?'selected':''}>Аварга</option><option ${p.title==='Арслан'?'selected':''}>Арслан</option><option ${p.title==='Заан'?'selected':''}>Заан</option><option ${p.title==='Начин'?'selected':''}>Начин</option><option ${p.title==='Аймгийн цолтон'?'selected':''}>Аймгийн цолтон</option></select></div><div class="card span6"><b>Шөвгийн 4</b>${multi('semi',p.semi||[],4)}<br><b>Шөвгийн 8</b>${multi('quarter',p.quarter||[],8)}</div><div class="span12"><button ${S.closed?'disabled':''} onclick="BTP.savePrediction()">Таавар хадгалах</button></div></div>`}
function changeEvent(v){S.activeTournament=v;save();render()}
function savePrediction(){if(S.closed)return toast('Таавар хаагдсан');let p=S.predictions.find(x=>x.userId===S.currentUser&&x.eventId===S.activeTournament);if(!p){p={id:uid(),userId:S.currentUser,eventId:S.activeTournament};S.predictions.push(p);let u=me();u.totalPredictions=(u.totalPredictions||0)+1}Object.assign(p,{champion:$('#champion').value,runner:$('#runner').value,province:$('#province').value,title:$('#title').value,semi:checks('semi').slice(0,4),quarter:checks('quarter').slice(0,8),updatedAt:new Date().toISOString()});save();toast('Таавар хадгалагдлаа');tab='mine';render()}
function mine(){let u=me();if(!u)return authBox();let ps=S.predictions.filter(x=>x.userId===u.id);return `<h2>Миний таавар</h2><div class="grid"><div class="card span4">${avatarHtml(u)}<h2>${u.name}</h2><div class="score">${u.score||0}</div><p class="muted">оноо</p></div><div class="card span8">${ps.map(predHtml).join('')||'<p class="muted">Та таавар өгөөгүй байна.</p>'}</div></div>`}
function predHtml(p){return `<div class="notice" style="margin-bottom:10px"><b>${(S.events.find(e=>e.id===p.eventId)||{}).name||'Наадам'}</b><p>Түрүү: ${wrestlerName(p.champion)}<br>Үзүүр: ${wrestlerName(p.runner)}<br>Шөвгийн 4: ${(p.semi||[]).map(wrestlerName).join(', ')}<br>Шөвгийн 8: ${(p.quarter||[]).map(wrestlerName).join(', ')}<br>Аймаг: ${p.province||'-'} · Цол: ${p.title||'-'}</p><span class="muted small">Оноо: ${p.calculatedScore||0}</span></div>`}
function board(){let province=localStorage.getItem(DB+'_filter')||'';let rows=[...S.users].filter(u=>!province||u.province===province).sort((a,b)=>(b.score||0)-(a.score||0)).slice(0,100).map((u,i)=>`<tr><td>${i+1}</td><td>${u.name}<div class="muted small">${u.province||'-'} · Lv ${u.level}</div></td><td>${u.xp||0}</td><td><b>${u.score||0}</b></td></tr>`).join('');return `<h2>Чансааны самбар</h2><div class="card"><label>Аймгаар шүүх</label><select onchange="BTP.filterProvince(this.value)"><option value="">Бүгд</option>${provinces.map(p=>`<option ${province===p?'selected':''}>${p}</option>`).join('')}</select><br><br><table class="table"><tr><th>#</th><th>Нэр</th><th>XP</th><th>Оноо</th></tr>${rows||'<tr><td colspan="4">Одоогоор хэрэглэгч алга.</td></tr>'}</table></div>`}
function filterProvince(v){localStorage.setItem(DB+'_filter',v);render()}
function profile(){let u=me();if(!u)return authBox();let pct=u.totalPredictions?Math.round((u.correctPredictions/u.totalPredictions)*100):0;return `<h2>Профайл</h2><div class="grid"><div class="card span4">${avatarHtml(u,true)}<h2>${u.name}</h2><p class="muted">${u.phone}</p><div class="score">${u.xp} XP</div><p>Level ${u.level}</p><div class="progress"><i style="width:${Math.min(100,(u.xp%150)/150*100)}%"></i></div><p class="muted small">Таасан хувь: ${pct}%</p>${(u.medals||[]).map(m=>`<span class="medal">🎖 ${m}</span>`).join('')||'<span class="medal">Шинэ гишүүн</span>'}</div><div class="card span8"><h2>Профайл засах</h2><label>Зураг URL</label><input id="pAvatar" value="${escapeAttr(u.avatar||'')}" placeholder="https://..."><br><br><label>Нэр</label><input id="pName" value="${escapeAttr(u.name||'')}"><br><br><label>Аймаг</label><select id="pProvince">${provinceOptions(u.province)}</select><br><br><label>Нас</label><input id="pAge" type="number" value="${escapeAttr(u.age||'')}"><br><br><button onclick="BTP.saveProfile()">Хадгалах</button></div></div>`}
function saveProfile(){let u=me();if(!u)return;u.avatar=$('#pAvatar').value.trim();u.name=$('#pName').value.trim()||u.name;u.province=$('#pProvince').value;u.age=$('#pAge').value;save();toast('Профайл хадгалагдлаа');render()}
function admin(){return `<h2>Админ самбар</h2><div class="grid"><div class="card span6"><h2>Нэвтрэх PIN</h2><input id="pin" placeholder="PIN"><br><br><button onclick="BTP.adminLogin()">Админ эрх нээх</button><p class="muted small">Одоогийн PIN: 1234</p></div><div class="card span6"><h2>Онооны дүрэм</h2>${Object.entries(S.settings.points).map(([k,v])=>`<p>${k}: <b>${v}</b></p>`).join('')}</div></div><div id="adminPanel">${sessionStorage.admin==='1'?adminPanel():''}</div>`}
function adminLogin(){if($('#pin').value===S.adminPin){sessionStorage.admin='1';toast('Админ нээгдлээ');render()}else toast('PIN буруу')}
function adminPanel(){let r=S.results||{};return `<div class="grid" style="margin-top:14px"><div class="card span4"><h2>Тааврын төлөв</h2><p>Одоо: <b>${S.closed?'Хаалттай':'Нээлттэй'}</b></p><button class="secondary" onclick="BTP.toggleClose()">${S.closed?'Нээх':'Хаах'}</button></div><div class="card span4"><h2>Наадам нэмэх</h2><input id="evName" placeholder="Наадмын нэр"><br><br><input id="evDate" type="datetime-local"><br><br><button onclick="BTP.addEvent()">Нэмэх</button></div><div class="card span4"><h2>Бөх нэмэх</h2><input id="newW" placeholder="Бөхийн нэр"><br><br><input id="newRank" placeholder="Цол"><br><br><select id="newProvince">${provinceOptions()}</select><br><br><button onclick="BTP.addWrestler()">Нэмэх</button></div><div class="card span12"><h2>Үр дүн оруулах</h2><div class="grid"><div class="span6"><label>Түрүү</label><select id="rChampion">${wrestlerOptions(r.champion)}</select></div><div class="span6"><label>Үзүүр</label><select id="rRunner">${wrestlerOptions(r.runner)}</select></div><div class="span6"><label>Аймаг</label><select id="rProvince">${provinceOptions(r.province)}</select></div><div class="span6"><label>Цол</label><select id="rTitle"><option>Аварга</option><option>Арслан</option><option>Заан</option><option>Начин</option><option>Аймгийн цолтон</option></select></div><div class="span6"><b>Шөвгийн 4</b>${multi('rSemi',r.semi||[],4)}</div><div class="span6"><b>Шөвгийн 8</b>${multi('rQuarter',r.quarter||[],8)}</div><div class="span12"><button onclick="BTP.saveResults()">Үр дүн хадгалж оноо бодох</button></div></div></div><div class="card span12"><button class="danger" onclick="BTP.resetDemo()">Demo өгөгдөл цэвэрлэх</button></div></div>`}
function toggleClose(){S.closed=!S.closed;save();render()}
function addEvent(){let name=$('#evName').value.trim();if(!name)return toast('Наадмын нэр оруул');S.events.push({id:uid(),name,type:'Барилдаан',date:$('#evDate').value?new Date($('#evDate').value).toISOString():new Date().toISOString(),status:'Таавар авч байна',location:''});save();toast('Наадам нэмэгдлээ');render()}
function addWrestler(){let v=$('#newW').value.trim();if(!v)return toast('Бөхийн нэр оруул');S.wrestlers.push({id:uid(),name:v,rank:$('#newRank').value.trim(),province:$('#newProvince').value,photo:''});save();toast('Бөх нэмэгдлээ');render()}
function saveResults(){S.results={eventId:S.activeTournament,champion:$('#rChampion').value,runner:$('#rRunner').value,province:$('#rProvince').value,title:$('#rTitle').value,semi:checks('rSemi').slice(0,4),quarter:checks('rQuarter').slice(0,8),savedAt:new Date().toISOString()};calculateScores();save();toast('Оноо бодогдлоо');tab='board';render()}
function calculateScores(){let P=S.settings.points,R=S.results;S.users.forEach(u=>{u.score=0;u.xp=0;u.correctPredictions=0});S.predictions.forEach(p=>{let sc=0,correct=0;if(p.eventId!==R.eventId)return;if(p.champion===R.champion){sc+=P.champion;correct++}if(p.runner===R.runner){sc+=P.runner;correct++}(p.semi||[]).forEach(x=>{if((R.semi||[]).includes(x)){sc+=P.semi;correct++}});(p.quarter||[]).forEach(x=>{if((R.quarter||[]).includes(x)){sc+=P.quarter;correct++}});if(p.province===R.province){sc+=P.province;correct++}if(p.title===R.title){sc+=P.title;correct++}if(p.champion===R.champion&&p.runner===R.runner&&(p.semi||[]).filter(x=>(R.semi||[]).includes(x)).length>=4)sc+=P.combo;p.calculatedScore=sc;let u=S.users.find(x=>x.id===p.userId);if(u){u.score+=sc;u.xp+=sc;u.correctPredictions=(u.correctPredictions||0)+correct;u.level=levelFromXp(u.xp);if(sc>=300 && !u.medals.includes('Мэргэн таамаглагч'))u.medals.push('Мэргэн таамаглагч')}})}
function resetDemo(){if(confirm('Бүх demo өгөгдлийг цэвэрлэх үү?')){localStorage.removeItem(DB);S=clone(defaultState);save();render()}}
window.BTP={setTab,login,logout,changeEvent,savePrediction,filterProvince,saveProfile,adminLogin,toggleClose,addEvent,addWrestler,saveResults,resetDemo,limitChecks};
window.addEventListener('load',()=>{normalizeState();save();render(); if('serviceWorker' in navigator){navigator.serviceWorker.register('sw.js').catch(()=>{})}});
setInterval(()=>{if(tab==='home')render()},1000);
})();
